### ISSUE TITLE
No logo/favicon

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/chatter#3]
We don't have a favicon yet, so our project is currently kinda lame. We ideally want a cute and bright logo!

**Comment by karenerosales** [comment]
![image](https://user-images.githubusercontent.com/78112330/234448262-3d2070ce-3186-44df-9e2d-5d509dbee2d6.png)

**Comment by diamondburned** [comment]
favicon added in 741b5a6f0b0668bf84f42e13ae33053f13f6b9c9. Thank you!
